export const NIGERIAN_UNIVERSITIES = [
  "Abia State University",
  "Achievers University",
  "Adamawa State University",
  "Adekunle Ajasin University",
  "Adeleke University",
  "Afe Babalola University",
  "African University of Science and Technology",
  "Ahmadu Bello University",
  "Ajayi Crowther University",
  "Akwa Ibom State University",
  "Al-Hikmah University",
  "Al-Qalam University",
  "Ambrose Alli University",
  "American University of Nigeria",
  "Anambra State University",
  "Arthur Jarvis University",
  "Augustine University",
  "Babcock University",
  "Bauchi State University",
  "Bayero University Kano",
  "Baze University",
  "Bells University of Technology",
  "Benson Idahosa University",
  "Benue State University",
  "Bowen University",
  "Caleb University",
  "Caritas University",
  "Chukwuemeka Odumegwu Ojukwu University",
  "Clifford University",
  "Coal City University",
  "Covenant University",
  "Crawford University",
  "Cross River University of Technology",
  "Crown Hill University",
  "Delta State University",
  "Dennis Osadebay University",
  "Dominican University",
  "Ebonyi State University",
  "Edwin Clark University",
  "Ekiti State University",
  "Elizade University",
  "Enugu State University of Science and Technology",
  "Federal University Birnin Kebbi",
  "Federal University Dutse",
  "Federal University Dutsin-Ma",
  "Federal University Gashua",
  "Federal University Gusau",
  "Federal University Kashere",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University Ndufu-Alike",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Federal University of Agriculture Abeokuta",
  "Federal University of Agriculture Markurdi",
  "Federal University of Petroleum Resources",
  "Federal University of Technology Akure",
  "Federal University of Technology Minna",
  "Federal University of Technology Owerri",
  "Fountain University",
  "Godfrey Okoye University",
  "Gregory University",
  "Hallmark University",
  "Hezekiah University",
  "Ibrahim Badamasi Babangida University",
  "Igbinedion University",
  "Imo State University",
  "Joseph Ayo Babalola University",
  "Kaduna State University",
  "Kebbi State University of Science and Technology",
  "Kogi State University",
  "Kwara State University",
  "Kwarafa University",
  "Lagos State University",
  "Landmark University",
  "Lead City University",
  "Legacy University",
  "Madonna University",
  "McPherson University",
  "Michael Okpara University of Agriculture",
  "Modibbo Adama University",
  "Mountain Top University",
  "Nile University of Nigeria",
  "Nnamdi Azikiwe University",
  "Novena University",
  "Obafemi Awolowo University",
  "Olabisi Onabanjo University",
  "Ondo State University of Science and Technology",
  "Pan-Atlantic University",
  "Paul University",
  "Plateau State University",
  "Redeemer's University",
  "Renaissance University",
  "Rivers State University",
  "Salem University",
  "Samuel Adegboyega University",
  "Sokoto State University",
  "Southwestern University",
  "Tai Solarin University of Education",
  "Tansian University",
  "Taraba State University",
  "Usmanu Danfodiyo University",
  "University of Abuja",
  "University of Agriculture Umudike",
  "University of Benin",
  "University of Calabar",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Nigeria Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Veritas University",
  "Wesley University",
  "Western Delta University",
  "Wellspring University",
  "Yobe State University",
  "Zamfara State University",
].sort();
