// Auto-generated seed data of motivational quotes for students.
// Rotated daily via getQuoteOfTheDay() in this file — no manual curation needed.
export interface Quote {
  text: string;
  author: string;
}

/** Deterministic seeded PRNG (mulberry32) so every user sees the same daily shuffle. */
function seededRandom(seed: number) {
  let t = seed;
  return () => {
    t |= 0;
    t = (t + 0x6d2b79f5) | 0;
    let r = Math.imul(t ^ (t >>> 15), 1 | t);
    r = (r + Math.imul(r ^ (r >>> 7), 61 | r)) ^ r;
    return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
  };
}

function seededShuffle<T>(items: T[], seed: number): T[] {
  const arr = items.slice();
  const rand = seededRandom(seed);
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * Returns today's quote. The full quote list is reshuffled once per cycle
 * (every QUOTES.length days) using the cycle number as a seed, then the day
 * within the cycle picks the position — so the order changes daily and the
 * whole set reshuffles once every ~200 days.
 */
export function getQuoteOfTheDay(date: Date = new Date()): Quote {
  const dayIndex = Math.floor(date.getTime() / DAY_MS);
  const cycle = Math.floor(dayIndex / QUOTES.length);
  const position = dayIndex % QUOTES.length;
  const shuffled = seededShuffle(QUOTES, cycle + 1);
  return shuffled[position];
}

export const QUOTES: Quote[] = [
  { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "You are never too small to make a difference.", author: "Greta Thunberg" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Your limitation—it's only your imagination.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Little things make big days.", author: "Unknown" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { text: "Don't wait for opportunity. Create it.", author: "Unknown" },
  { text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
  { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { text: "Dream bigger. Do bigger.", author: "Unknown" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
  { text: "What seems impossible today will one day become your warm-up.", author: "Unknown" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
  { text: "I never dreamed about success. I worked for it.", author: "Estée Lauder" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "You can't build a reputation on what you are going to do.", author: "Henry Ford" },
  { text: "Knowing is not enough; we must apply.", author: "Leonardo da Vinci" },
  { text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Winners are not people who never fail, but people who never quit.", author: "Unknown" },
  { text: "A river cuts through rock, not because of its power, but its persistence.", author: "Jim Watkins" },
  { text: "One gig at a time, you're building the résumé no classroom can teach.", author: "Skillz" },
  { text: "Your side hustle today is your headline tomorrow.", author: "Skillz" },
  { text: "Skills pay bills — keep sharpening yours.", author: "Skillz" },
  { text: "You don't need a full-time job to have a full-time hustle.", author: "Skillz" },
  { text: "Every application you send is a rep. Reps build muscle.", author: "Skillz" },
  { text: "Consistency turns a student into a professional.", author: "Skillz" },
  { text: "The gig you almost didn't apply for could be the one that changes everything.", author: "Skillz" },
  { text: "Get paid to get good — that's the campus advantage.", author: "Skillz" },
  { text: "Your portfolio grows one small win at a time.", author: "Skillz" },
  { text: "Rejections are just redirections toward the right client.", author: "Skillz" },
  { text: "Show up for the ₦2,000 gig the same way you'd show up for the ₦200,000 one.", author: "Skillz" },
  { text: "Reputation is currency. Protect it with every gig you take.", author: "Skillz" },
  { text: "The best time to build your brand was yesterday. The next best time is now.", author: "Skillz" },
  { text: "You're not 'just a student' — you're a professional in training.", author: "Skillz" },
  { text: "Every skill you list should be a skill you can prove.", author: "Skillz" },
  { text: "Freelancing while studying isn't a distraction, it's an education.", author: "Skillz" },
  { text: "Your first client is rarely your biggest — but they're your proof of concept.", author: "Skillz" },
  { text: "Deadlines don't care about lectures. Manage both like a pro.", author: "Skillz" },
  { text: "Confidence comes from finished work, not perfect plans.", author: "Skillz" },
  { text: "A verified profile opens doors a CV alone cannot.", author: "Skillz" },
  { text: "You're one referral away from your next big opportunity.", author: "Skillz" },
  { text: "Small gigs, done well, become big referrals.", author: "Skillz" },
  { text: "Discipline today is the freedom you'll enjoy after graduation.", author: "Skillz" },
  { text: "Every 'no' is data. Every 'yes' is momentum.", author: "Skillz" },
  { text: "Your network on campus is your net worth off campus.", author: "Skillz" },
  { text: "Build in public — let your work speak before you do.", author: "Skillz" },
  { text: "The hustle doesn't pause for exams; it just gets smarter.", author: "Skillz" },
  { text: "You are the CEO of your own campus economy.", author: "Skillz" },
  { text: "Talent gets noticed. Consistency gets hired.", author: "Skillz" },
  { text: "Do the work nobody sees, so the results everyone sees make sense.", author: "Skillz" },
  { text: "Your rating is your resume — earn every star.", author: "Skillz" },
  { text: "One completed gig is worth ten unfinished plans.", author: "Skillz" },
  { text: "Show clients your work, not your excuses.", author: "Skillz" },
  { text: "The gig economy rewards those who show up twice: once to apply, once to deliver.", author: "Skillz" },
  { text: "You don't need permission to start earning from your skills.", author: "Skillz" },
  { text: "Every completed project is a brick in the wall of your career.", author: "Skillz" },
  { text: "Your bio is your pitch — make every word earn its place.", author: "Skillz" },
  { text: "Great portfolios are built gig by gig, not overnight.", author: "Skillz" },
  { text: "The student who finishes strong outworks the one who starts fast.", author: "Skillz" },
  { text: "Chase skills, not just certificates.", author: "Skillz" },
  { text: "Your WhatsApp status could be your next client's first impression.", author: "Skillz" },
  { text: "Turn free time into paid time — one gig at a time.", author: "Skillz" },
  { text: "The campus hustle is real practice for the real world.", author: "Skillz" },
  { text: "Your profile score isn't vanity — it's visibility.", author: "Skillz" },
  { text: "Clients hire clarity. Be clear about what you offer.", author: "Skillz" },
  { text: "You're not competing with classmates — you're competing with yesterday's you.", author: "Skillz" },
  { text: "Every skill you add to your profile is a door you didn't have before.", author: "Skillz" },
  { text: "The gig you finish today builds the trust you need tomorrow.", author: "Skillz" },
  { text: "Momentum beats motivation. Keep moving.", author: "Skillz" },
  { text: "Your first ₦500 gig and your first ₦50,000 gig both deserve your best work.", author: "Skillz" },
  { text: "Grow loud in skill, stay humble in hustle.", author: "Skillz" },
  { text: "The market rewards students who treat gigs like careers.", author: "Skillz" },
  { text: "Your profile is a storefront — keep it open, keep it fresh.", author: "Skillz" },
  { text: "Success on campus starts with one completed application.", author: "Skillz" },
  { text: "Show up early, deliver on time, and your name will travel.", author: "Skillz" },
  { text: "You're not too busy — you're just not prioritized yet. Fix that.", author: "Skillz" },
  { text: "The best portfolio piece is the one you haven't started yet. Start it.", author: "Skillz" },
  { text: "Get comfortable being uncomfortable — that's where growth lives.", author: "Skillz" },
  { text: "Every skill you master today is income you haven't collected yet.", author: "Skillz" },
  { text: "Your reputation follows you further than your GPA ever will.", author: "Skillz" },
  { text: "Progress over perfection — ship the gig, then improve.", author: "Skillz" },
  { text: "The student who learns to sell their skill never lacks opportunity.", author: "Skillz" },
  { text: "Referrals are proof that your work speaks for itself.", author: "Skillz" },
  { text: "You build credibility one delivered gig at a time.", author: "Skillz" },
  { text: "Your next big break might be one profile update away.", author: "Skillz" },
  { text: "Treat every client like your last — they'll treat you like your next big one.", author: "Skillz" },
  { text: "Time on campus is limited. Skills built here last a lifetime.", author: "Skillz" },
  { text: "You don't rise to the level of your goals, you fall to the level of your habits.", author: "Skillz" },
  { text: "A completed profile is a decision to be found.", author: "Skillz" },
  { text: "Talent whispers. Consistency shouts.", author: "Skillz" },
  { text: "The hustle is a marathon disguised as a hundred small sprints.", author: "Skillz" },
  { text: "Your skillset is your safety net — keep weaving it.", author: "Skillz" },
  { text: "Real growth happens between the gig you wanted and the gig you got.", author: "Skillz" },
  { text: "Show clients your receipts, not your résumé.", author: "Skillz" },
  { text: "The campus hustle rewards patience as much as hustle.", author: "Skillz" },
  { text: "You're building a brand every time someone reads your profile.", author: "Skillz" },
  { text: "Learn it, list it, live it — that's how skills become income.", author: "Skillz" },
  { text: "Every skill you teach yourself is a raise nobody can take back.", author: "Skillz" },
  { text: "Don't wait to feel ready. Apply, then grow into the gig.", author: "Skillz" },
  { text: "The student hustle is proof that ambition doesn't wait for graduation.", author: "Skillz" },
  { text: "Your portfolio should scare your competition and inspire your clients.", author: "Skillz" },
  { text: "Deliver quietly, let your reviews do the talking.", author: "Skillz" },
  { text: "You are one gig closer to the career you're imagining.", author: "Skillz" },
  { text: "The best investment on campus is in your own skillset.", author: "Skillz" },
  { text: "Every task completed on time is trust deposited for the next one.", author: "Skillz" },
  { text: "Skills compound like interest — start earning both today.", author: "Skillz" },
  { text: "Your hustle today writes the story your résumé can't.", author: "Skillz" },
  { text: "Show up for the small gigs — they build the muscles for the big ones.", author: "Skillz" },
  { text: "The market doesn't care about your major, only your delivery.", author: "Skillz" },
  { text: "You are always one skill away from your next opportunity.", author: "Skillz" },
  { text: "Consistency is the quiet superpower of every top-rated student.", author: "Skillz" },
  { text: "Your profile photo is a handshake — make it firm and friendly.", author: "Skillz" },
  { text: "The gig you complete today is the testimonial you'll need tomorrow.", author: "Skillz" },
  { text: "Chase clarity in your bio, and clients will chase you.", author: "Skillz" },
  { text: "Every skill listed should have a story behind it — live those stories.", author: "Skillz" },
  { text: "You don't need a big break. You need a hundred small ones, stacked.", author: "Skillz" },
  { text: "Turn your free periods into your funded periods.", author: "Skillz" },
  { text: "The most valuable class on campus is the one you teach yourself.", author: "Skillz" },
  { text: "Your rating grows every time you overdeliver on a small promise.", author: "Skillz" },
  { text: "The best résumé line is 'delivered on time, every time.'", author: "Skillz" },
  { text: "Skills are the one asset that appreciate with every gig you take.", author: "Skillz" },
  { text: "Show up for your profile the way you show up for your finals.", author: "Skillz" },
  { text: "Your next referral is one great delivery away.", author: "Skillz" },
  { text: "You're not just earning money — you're earning proof you can be trusted with more.", author: "Skillz" },
  { text: "The gig economy is patient with beginners who are consistent.", author: "Skillz" },
  { text: "Build your name before you need it — reputation compounds slowly.", author: "Skillz" },
  { text: "Every completed gig quietly upgrades your next opportunity.", author: "Skillz" },
  { text: "You are one application away from a client who changes everything.", author: "Skillz" },
  { text: "Skills you build for survival today become the career you love tomorrow.", author: "Skillz" },
  { text: "The hustle isn't about hours, it's about who you become in them.", author: "Skillz" },
  { text: "Your first client teaches you more than your first semester.", author: "Skillz" },
  { text: "Show clients consistency and they'll show you loyalty.", author: "Skillz" },
  { text: "Every skill you add to your profile is a bet on your future self.", author: "Skillz" },
  { text: "You build your brand in the gaps between lectures.", author: "Skillz" },
  { text: "The student who finishes gigs on time never runs out of gigs.", author: "Skillz" },
  { text: "Your portfolio is a museum of proof — keep adding to it.", author: "Skillz" },
  { text: "Skills unused are opportunities untouched. Put yours to work.", author: "Skillz" },
  { text: "The best marketing for your skills is a job well done.", author: "Skillz" },
  { text: "You are the sum of every gig you didn't skip.", author: "Skillz" },
  { text: "Your profile is quiet until you make it loud with results.", author: "Skillz" },
  { text: "Every rating you earn is a brick in the trust you're building.", author: "Skillz" },
  { text: "Show up small today so you can show up big tomorrow.", author: "Skillz" },
  { text: "The hustle doesn't ask for permission, only for your next move.", author: "Skillz" },
  { text: "Your first ₦1,000 gig is proof the market believes in you.", author: "Skillz" },
  { text: "Skills grow in public, one client review at a time.", author: "Skillz" },
  { text: "You don't need to be the best on campus, just the most consistent.", author: "Skillz" },
  { text: "The student who keeps applying eventually stops needing to.", author: "Skillz" },
  { text: "Every gig is a classroom the syllabus never mentioned.", author: "Skillz" },
  { text: "Your name is your brand — spell it right in every delivery.", author: "Skillz" },
  { text: "Show up for the gig no one's watching; that's where character is built.", author: "Skillz" },
  { text: "You're not behind — you're building at your own pace, on purpose.", author: "Skillz" },
  { text: "The gig you're avoiding is probably the one that grows you most.", author: "Skillz" },
  { text: "Your CV lists degrees. Your profile proves skills — build both.", author: "Skillz" },
  { text: "A single great review can outweigh a hundred silent ones. Ask for it.", author: "Skillz" },
  { text: "Every skill mastered is a bill you'll never worry about again.", author: "Skillz" },
  { text: "You are not too young to be taken seriously — deliver, and you will be.", author: "Skillz" },
  { text: "Show up for your Monday gig like it's your dream job — it's training for it.", author: "Skillz" },
  { text: "The market pays for solved problems, not stated skills. Solve one today.", author: "Skillz" },
  { text: "Your hustle is a compound account — deposit consistently, withdraw later.", author: "Skillz" },
  { text: "A finished gig beats a perfect plan every single time.", author: "Skillz" },
  { text: "Skills you practice in silence get discovered in public.", author: "Skillz" },
  { text: "Every client you delight becomes a billboard for your talent.", author: "Skillz" },
  { text: "You're building two things at once: a skillset and a story.", author: "Skillz" },
];
